# Generated by Django 3.1.4 on 2020-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomedi', '0002_news_showbiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=300)),
                ('preferred_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
